Repository neo4j/cypher-language-support, pull requests merged in 2025-03, with the labels that each got.

#385 Adds neo4j+ssc and bolt+ssc as connection options
  packages/vscode-extension/src/connectionService.ts
  packages/vscode-extension/src/webviews/connectionPanel.ts
  packages/vscode-extension/src/webviews/controllers/connectionPanelController.ts
Labels: enhancement

#419 Fetches dev artifacts (grammar and semantic analysis js) from AWS
  .github/workflows/fetch-dev-artifacts.yaml
Labels: depends on semantic analysis, convenience

#442 Adds icons to edit/delete params, better error message when setting against system
  package-lock.json
  packages/vscode-extension/package.json
  packages/vscode-extension/src/commandHandlers/connection.ts
  packages/vscode-extension/src/commandHandlers/params.ts
  packages/vscode-extension/src/constants.ts
  packages/vscode-extension/src/parameterService.ts
  packages/vscode-extension/src/registrationService.ts
  packages/vscode-extension/tests/specs/webviews/params.spec.ts
Labels: vscode
